### ISSUE TITLE
Working Directories

### ISSUE THREAD

**Issue by joangui** [rpau/walkmod-core#17]
It would be helpful if, instead of having to copy the content of the walkmod.xml file from the web, walkmod was able to set a given directory as a walkmod working directory.

Say for instance:

$> walkmod --setWorkingDirectoy="$PATH"

and that would create automatically the walkmod.xml file in $PATH, and any other infrastructure that is (or may be in a future) required. That would make walkmod more self-contained.

(btw, nice work!)

**Comment by rpau** [comment]
Fixed in the following commit on the "dev" branch:
 c3291b1014b1366fbac83080617728f9bc628b2b 

It allows to run 2 commands to avoid writing the xml file:

walkmod add-plugin --groupId org.walkmod --artifactId walkmod-imports-cleaner-plugin --version 2.0
walkmod add-chain -d src --walker { transformations :[ { type: "walkmod:commons:import-cleaner"} ] }

**Comment by rpau** [comment]
Improved:

Now, the following command is enough:
walkmod add -d WORKINGDIR imports-cleaner

It is available in master branch and ready to download from https://bitbucket.org/rpau/walkmod/downloads/walkmod-2.0-installer.zip
