### ISSUE TITLE
[enhancement] Create a single unified method for WalkmodFacade

### ISSUE THREAD

**Issue by rpau** [rpau/walkmod-core#18]
_From @abelsromero on August 29, 2015 9:36_

_As a developer/integrator I'd like to be able to launch walkmod chains through a single method, no matter what configuration I am passing or how the chains are defined._

I've seen that right now the facade offers many methods whose only difference is the number of parameters (error handling, vebose, etc.). Also some require to set the configuration as a [file](https://github.com/rpau/walkmod-core/blob/master/src/main/java/org/walkmod/WalkModFacade.java#L104), and some as a [path](https://github.com/rpau/walkmod-core/blob/master/src/main/java/org/walkmod/WalkModFacade.java#L126).

This approach is correct with the current set of settings, but hinders the possibility to pass more features that may appear in the future.
What I am proposing is creating a single method with the following specification:
* A `Map<String, Object>` object: each parameter can be set with a predefined key: "verbose", "offline", etc. This allows to pass even real object, that could be injected in the context. To ease the configuration, some helper class can be created (here is an example [OptionsBuilder](https://github.com/asciidoctor/asciidoctorj/blob/master/asciidoctorj-core/src/main/java/org/asciidoctor/OptionsBuilder.java)). Optionally, an overloaded method with the helper method could be offered. As an example of future option I'd like to be able to set the base directory for the walkers/visitors, so I can have a folder with the walkmod file in a parent project and the apply the changes to child projects without having to copy it to each one.
* `ConfigurationProvider` instance: right now is it possible to use other providers instead of Ivy, however, the Facade does not allow it. Btw, nothing against ivy, but in corporate enviroments (with proxy and shitty network) Ivy's bootstrap can take quite a long time, whereas being able to pass a direct classloader alreay initialize (e.g. by maven or gradle) can remove that time and simplify the integration with other tools.
* `File or String` walkmod file: I preffer a File, but the main point is defining a single point of entry. I don't have a strong opinion on either options as long as one single option is set. Also I'm thinking that the "walkmod file" could be passed with some interface or wrapper. In the future it would be cool to be able to pass a configuration in some other way, like an object created with a DSL. Anyway, that can be done in the future. wdyt? Should walkmod define it or stick with the file/path? imho, It's a shame ConfigurationProvider name is already taken ><

Current methods can be marked as @deprecated. 

Overall, this proposal avoid changes in the integrators interface regarding the evolution of the API, and makes the Facede more firendly not only to Java but to other languages like Groovy.

wdyt?

_Copied from original issue: rpau/walkmod-cmd#2_

**Comment by rpau** [comment]
Hi Abel,

In general, I agree with you with the API that you suggest. I think that are good ideas that can make this API easier to use. 

I think that the first suggestion is necessary, because all started from few options and now it becomes more difficult to set every option. I really would like to have an `OptionBuilder`.

Regarding the second and third point, I think that you are designing the already existing class called `org.walkmod.conf.ConfigurationManager.ConfigurationManager` , which allows to pass the walkmod file (which could be another interface, and the list of `ConfigurationProvider`s). In fact, this is the class that the `WalkmodFacace` uses internally. Isn't it?

How do you want to proceed whatever we decide? Create a pull request or do you need that I apply the changes?

**Comment by rpau** [comment]
_From @abelsromero on August 30, 2015 11:42_

> How do you want to proceed whatever we decide? Create a pull request or do you need that I apply the changes?

If it's OK for you, you can create a development branch and I can send a PR there.

> Regarding the second and third point, I think that you are designing the already existing class called org.walkmod.conf.ConfigurationManager.ConfigurationManager , which allows to pass the walkmod file (which could be another interface, and the list of ConfigurationProviders). In fact, this is the class that the WalkmodFacace uses internally. Isn't it?

You are right. I'll work arround the idea of using ConfigurationManager and see what I can get. Once the PR is sent we can see alternatives and keep the discussion on it.

Btw, I messed the issue opening it in the wrong project. Can you move it? I have used this before it works quite well: https://github-issue-mover.appspot.com/.

**Comment by rpau** [comment]
The new branch called "dev" has been created in walkmod-core.

Thank you for all your feedback and the recommendation of the github-issue-mover :+1:

**Comment by abelsromero** [comment]
I'll try to send the PR something during this week.

**Comment by abelsromero** [comment]
I'm documenting the options in the JavaDocs but I think I don't understand what include/exclude does.
Can you explain a bit and show how to conigure it on a command execution. I debuged WalkModDispather and saw that my include path is detected and validated, but no code is generated.

Thanks,

**Comment by rpau** [comment]
Hi Abel,

When I was building the walkmodhub service I needed to run walkmod just for the set of files modified or created in the last push. The reason is because people do not want to review changes that are not related with the last action. Therefore,  I needed to tell walkmod: overwrite the current include/exclude rules in the reader for these set of files. 

Take into account that is different a null value than an String[] for includes/excludes. An empty String[] represents includes nothing /excludes all. Which value are you passing? 

Walkmod has in the bin folder a walkmodDebug binary. You can run it and debug walkmod remotely to see the differences.

**Comment by abelsromero** [comment]
After testing several things I went for the simple option (File, Map, ConfigurationProvider).
It works but I feel it won't be the last version and we may need to iterate.

Regarding the use of ConfigManager, I see it takes care all ConfigurationProvider, and I was thinking in something independent. Looking deeper I see that the config file is handled by `XMLConfigurationProvider` another ConfigurationProvider. This makes sense but exposing the file as a ConfigurationProvider may be confusing for some people. I think that currently we can work with a File.

About the use of the ConfigurationProvider to replace Ivy's resolution, it works. I'm still integrating it into the gradle plugin, and so-far-so-good, but I'm duplicating some code from IvyConf.Provider. Maybe we could split Ivy's CondifurationProvider it into two classes:
* And Abstract one doing the plugin parsing
* The resolver which sets the classloader.
Then, the interface instead of a ConfigurationProvider could accept the new abstract one. This makes clear the fucntion of the parameter

One minnor thing worth commenting, I renamed the option "ThrowsException" to "ThrowException" to align it with the "printError" variable.

**Comment by rpau** [comment]
Hi Abel,

I have designed this part very similar than Struts2 / XWorks frameworks . The idea was that the configuration may come from different files / resources and the project won't be coupled to any specific way to load the configuration. This is the reason why exists the ConfigManager. Consequently, it becomes easy to, for example, extend or replace the configuration loading process.

Ok, I agree to create an abstract class to manage the general behavior for loading the plugins classpath. So, are you using the Gradle API to load the plugins from your gradle plugin? Is it faster?

Ok, to the renaming.

**Comment by abelsromero** [comment]
> Ok, I agree to create an abstract class to manage the general behavior for loading the plugins classpath.

I'll update the PR for convenience, but I'll keep the interface with ConfigurationProvider. You convinced me in keeping the flexibility, it can be usefull in the future.

> So, are you using the Gradle API to load the plugins from your gradle plugin? Is it faster?

So far I made a few test but is faster, specially when resolving version ranges, I think because gradle does not check the remote repos everysingle time.
My final goal is to offer a gradle configuration to define plugins. That way all the resolution is handled by gradle and people don't need to deal with other tools in they build process. Still if someone wants can use Ivy, they'll be able, but I think it makes sense to keep dependency logic in Gradle and leave walkmod only to execute the chains. It also means you only need to setup the network config for Ivy (hell I do hate proxy settings ><).

The gradle configuration will look something like this:
```
dependencies {
    compile "log4j:log4j:1.2.17"
    compile "...."
    testCompile 'org.springframework:spring-test:4.1.7.RELEASE'

    walkmod 'org.walkmod:artifactId:walkmod-imports-cleaner-plugin:2.0'
}

```

In case of doubts, my main objective is to get good gradle integration :P Expect many more PRs in that direction.
Overall, I think walkmod and gradle are a perfect match and with current Gradle-IDEs integration you could really make walkmod something easy to use in your projects. My previous experiences with Walkmod were not positive because devs required to switch to command line, mess with the XML, and Ivy was a p*** with our network.

**Comment by rpau** [comment]
Great to use about Gradle instead of Ivy if it works faster :+1: 

In fact, if it works fine, I would like to replace Ivy for Gradle in a major version of walkmod :-) and let developer to choose between them by config.

**Comment by abelsromero** [comment]
You can close this issue
