### ISSUE TITLE
Passing paramaters to ConfigurationProviders

### ISSUE THREAD

**Issue by abelsromero** [rpau/walkmod-core#27]
I'm trying to implement a way to set the base directory for an execution and I have some doubts regarding to how pass the parameter.
Basically, the use case I want to fulfill is: "I want to execute some chain, and set as root for the execution some path that is not the current execution directory". I just need to pass a path, and prefix this to the walker, reader and writers paths found in the XML.

The thing is that I find that using a ConfigurationProvider to pass that information is not useful, because I need to pass the extra parameter to other ConfigurationProviders so that they can use that information to initialize instances (more precisely the XMLConfigurationProvider needs the base path).
As an alternative I can add the extra parameter to the `paramaters` Map in the Configuration instance and then copy them to the ChainAdapter in the ChainAdapterFactory, and finally, use them to modify the already initialized instances in the `prepare` method. Overall, this is a pain and this solution won't be valid if this "base directory" option is ever added to the XML as a tag/property.

For a simple common solution I think it would be usefull to review how ConfigurationManager works.
As far as I understand:
* The simple constructors are not used.
* The constructor being used ([ConfigurationManager#L42](https://github.com/rpau/walkmod-core/blob/master/src/main/java/org/walkmod/conf/ConfigurationManager.java#L42)) does not allow to customize a Configuration instance. Instead, it creates an empty instance that is then passed to all ConfigurationProviders.

I feel that the `Configuration` and the `parameters` Map instance is just what I need. What do you think about modifing the constructor to also recieve a Configuration?
I'm open to all suggestions.
As a side note, I have my doubts about all the initialization done in the ConfigurationProvider. Maybe it should be moved to another class that initialized Walkmod. That way we could avoid some duplicated code in the Facade...but maybe I'm overthinking ^^''

**Comment by rpau** [comment]
Hi,

My humble opinion is that it is not a good idea to manage the "execution directory" as a parameter, because any transformation (or any other walkmod component : walkers or writers), should be able to execute `new File("something")` and be sure that it will be created into the correct place. Otherwise, this change may provoke that plugins become more error pruning. 

So, for me, the solution is to create an new Java process in the new execution dir with the `ProcessBuilder`API like this (https://gist.github.com/rpau/08ccf5fbd4e4fe463e3c). Probably, it should be a parameter of the OptionsBuilder.

In fact, I need this feature too to use walkmod in maven multimodules projects. Let me create a branch just for it and we can merge into the dev branch when we agree.

**Comment by abelsromero** [comment]
> My humble opinion is that it is not a good idea to manage the "execution directory" as a parameter, because any transformation (or any other walkmod component : walkers or writers),

Absolutely agree. That's why I feel a ConfigurationProvider does not match this needs. I'm well aware that this is no easy task and many cases must be taken into consideration.


> So, for me, the solution is to create an new Java process in the new execution dir with the ProcessBuilderAPI like this (https://gist.github.com/rpau/08ccf5fbd4e4fe463e3c). Probably, it should be a parameter of the OptionsBuilder.

Seeing how the maven plugin is implemented, this means changing completely how it works. I'm not sure this will work.
Also, I don't want to create a new process, this means starting a new full Java stack which is time and memory, setting the classpath, etc. Not to mentions that you need to add some mechanisms to syncronize the execution and handle exceptions :%

**Comment by rpau** [comment]
The maven-walkmod-plugin will work, because the separate process just will be executed when the desired execution directory is different than the current one. Could you let me know why is the purpose to run walkmod in a different directory? How many executions do you will apply for a project?

In fact, I think that it is exactly what maven does when the user is building a project with multi-modules. In fact, for the walkmodhub, I was looking for something that "replace" the Java "user.dir" value, and it didn't work. Check http://stackoverflow.com/questions/840190/changing-the-current-working-directory-in-java

Now, reading a little bit more, I have found this way http://stackoverflow.com/questions/840190/changing-the-current-working-directory-in-java/8204584#8204584
There is a library that allows to do that using JNI. I will try :+1:

**Comment by abelsromero** [comment]
> The maven-walkmod-plugin will work, because the separate process just will be executed when the desired execution directory is different than the current one. Could you let me know why is the purpose to run walkmod in a different directory? How many executions do you will apply for a project?

First thing is to be able to add tests, so that we can have folders with different walkmod examples and run them from junit. Also, I think it's a nice option to have to allow more freedon in how the files are set in projects. For instance, in Gradle it would allow me to keep the configuration in the parent module and create a task for each sub-project. Another use case is using walkmod in a CI environment so that users don't need to set walkmod locally.
Not convinced yet this is a nice feature to integrate? :wink: 

> Now, reading a little bit more, I have found this way http://stackoverflow.com/questions/840190/changing-the-current-working-directory-in-java/8204584#8204584
> There is a library that allows to do that using JNI. I will try

Excelent news! And it should work for console executions, in fact this could be an option for "fork/paralel" executions. But still I see some problems like the exception handling when using walkmod from Java.

**Comment by rpau** [comment]
I have pushed in my branch called multimodule the required changes. Now, there is another possible value in `Options` and `OptionsBuilder` to set the execution directory. 

I have found a bug on walkmod-javalang-plugin related with it. I am fixing it and deploying a new version.

Once, fixed, I will apply a PR to the dev branch.

**Comment by abelsromero** [comment]
> I have found a bug on walkmod-javalang-plugin related with it. I am fixing it and deploying a new version.

Seems to me like next release is going to be awesome!

**Comment by rpau** [comment]
Done! :-)
